$ANSIBLE_VAULT;1.1;AES256
66376431356365316533313566383838353137656262393561383638383634353966653465316231
6139666266366462303565616333393764346664376435390a306338373765653533613566303935
31386539653134393136353133346362656238663834326461333765313833393034383631666339
6331343930663235610a636234366334353939623661326131343466343633303561633030323732
62373233616538396535633162306636643339373930656461316635393539626466303434373336
64616439313231346366323863613731373632343136663066636536366331613739306539643232
39363433353338626135333937303462373965633433656564653336323434306632653537623036
63303337343939653831306235346139643665373262633830353261636539653231303565373962
34373635383333383833366466313232316131313161393135623037326630616330336630313662
61623063343764323665373430396234613030636332313664666166343738343930333832623361
65306534623032356231656264373162333233313066363130623537366661633061336439396265
63396264366234646533383135303063313831636431336236383864393063633534633731643030
38643536326539613563616535383433653839376464303339653437643865633936356339653832
63393730346363633761373763366561633265623466313031653138396434306534383337623132
63306331656538646636326139383763336431336166633537363964346663316561633431303264
33636331663530666564
